### ISSUE TITLE
It doesn't seem to be working!

### ISSUE THREAD

**Issue by sergioferrari** [GiovanniDicanio/PrintUnicodeTextToConsoleWin#1] opened 2024-04-14 09:56 UTC
Hi, John! I simply compiled and started the program, but the result is as follows: 

<img width="494" alt="GioDicanioUnicode" src="https://github.com/GiovanniDicanio/PrintUnicodeTextToConsoleWin/assets/49869701/c2caf57e-2ecb-4012-ac59-534f34f487d5">

**Comment by GiovanniDicanio** [comment] 2024-04-14 14:12
Hi,

Did you set a proper font that can display the Japanese kanji?

I mentioned that in the associated blog post:

https://giodicanio.com/2023/06/01/how-to-print-unicode-text-to-the-windows-console-in-c-plus-plus/

Note that the *font* you use in the Windows console must support the
characters you want to print; in this example, I used the *MS Gothic* font
to show the Japanese kanjis.




Il giorno dom 14 apr 2024 alle 11:57 Sergio Ferrari <
***@***.***> ha scritto:

**Comment by GiovanniDicanio** [comment] 2024-04-16 16:05
Since my code does work, as I have shown in the screenshot in my blog post, and you haven't followed up, I'm closing this issue. If you have more details and reproducible steps, feel free to follow up.

**Closed as completed by GiovanniDicanio** 2024-04-16 16:05 UTC
